Repository rms-support-letter/rms-support-letter.github.io, pull requests merged in 2021-03, with the labels that each got.

#162 Signed
  README.md
Labels: needs changes

#391 Index.md signed by Maxim Polishchuk
  index.md
Labels: ready to merge

#390 Sign
  index.md
Labels: ready to merge

#389 Add signature
  index.md
Labels: ready to merge

#388 Signed
  index.md
Labels: ready to merge

#387 Signed
  index.md
Labels: ready to merge

#386 Update index.md
  index.md
Labels: ready to merge

#385 Sign
  index.md
Labels: ready to merge

#384 Sign
  index.md
Labels: ready to merge

#383 Signed
  index.md
Labels: ready to merge

#382 add name
  index.md
Labels: ready to merge

#381 Signed
  index.md
Labels: ready to merge

#380 Update index.md
  index.md
Labels: ready to merge

#379 Signed!
  index.md
Labels: ready to merge

#378 Signed
  README.md
  index.md
Labels: ready to merge

#377 Sign
  index.md
Labels: ready to merge

#375 Sign a letter to support RMS
  index.md
Labels: ready to merge

#374 Sign
  index.md
Labels: ready to merge

#373 Support RMS
  index.md
Labels: ready to merge

#372 Update index.md
  index.md
Labels: ready to merge

#371 Sign
  index.md
Labels: ready to merge

#370 Sign
  index.md
Labels: ready to merge

#333 signed
  index.md
Labels: ready to merge

#369 Signed
  index.md
Labels: ready to merge

#999 Fix yamls
  README.md
  _data/signed/NickKush.yaml
  _data/signed/ThatBlend.yml
  _data/signed/VolkerWeiBmann.yaml
  _data/signed/Yaroslew.yaml
  _data/signed/alcortazzo.yaml
  _data/signed/exclaveh.yaml
  _data/signed/im.yaml
  _data/signed/koyafish.yaml
  _data/signed/krafting.yaml
  _data/signed/yahorosh.yaml
Labels: priority

#1006 Create pull_request_template.md
  .github/pull_request_template.md
Labels: priority

#718 Structure that makes more sense
  _layouts/letter.html
  _layouts/signed.html
  index.md
Labels: priority

#240 add padenmoss
  _data/signed/padenmoss.yaml
Labels: ready to merge

#259 sign
  _data/signed/r-novel.yaml
Labels: ready to merge

#276 sign
  _data/signed/azazellochg.yaml
Labels: ready to merge

#277 Add signature
  _data/zlopez.yaml
Labels: ready to merge

#343 Signed
  _data/signed/phpoenx.yaml
Labels: ready to merge

#359 Sign
  _data/signed/MonkAlex.yaml
Labels: ready to merge

#365 signed
  _data/signed/DmHertz.yaml
  index.md
Labels: ready to merge

#1566 Add EvanMeek sign.
  README_ZH-CN.md
  _data/signed/EvanMeek.yaml
Labels: priority

#1563 SODIX[BANNED EVERYWHERE, FOREVER].yaml
  _data/signed/SODIX[BANNED EVERYWHERE, FOREVER].yaml
Labels: needs changes

#1554 Translated index.md to Spanish
  index_es.md
Labels: priority

#1536 Added my name and translated index.md to PT-BR, because the open letter had it translated too
  _data/signed/MrExcaliburBr.yaml
  index-pt-br.md
Labels: priority

#1752 Translate README to Romanian, fix typo in README
  README.md
  README_RO.md
Labels: priority

#1832 Add German translation
  _layouts/signed.html
  index_de.md
Labels: translation

#1793 Improve Romanian translations.
  README_RO.md
  index_ro.md
Labels: translation

#1808 Translate README to Russian
  README_RU.md
Labels: translation

#1864 Fixed errors in index_pt_br.md
  index_pt_br.md
Labels: translation

#1874 French traduction
  _layouts/signed.html
  index_fr.md
Labels: translation

#1897 translation stuff
  README_FR.md
  index_es.md
  index_pt_br.md
  index_ro.md
  index_tr.md
Labels: translation

#1928 add Polish translation
  README_PL.md
  index_pl.md
Labels: translation

#1895 Update index_de.md
  index_de.md
Labels: translation

#1981 _layouts/signed.html: add link to Polish translation
  _layouts/signed.html
Labels: translation

#2006 Paweł Standowicz
  _data/signed/Pawel82S.yaml
Labels: needs changes

#2009 Create jerabekmichal.yaml
  _data/signed/jerabekmichal.yaml
Labels: needs changes

#2008 README Korean translation added
  README_KO.md
Labels: translation

#2046 Fix typos in the french translation
  index_fr.md
Labels: translation

#2061 Create README_UA.md (Ukarinian)
  README_UA.md
Labels: translation

#2101 Fixes minor grammatical peeves
  index_de.md
Labels: translation

#2087 Add Korean translation + sign
  _data/signed/greenhorse-effect.yaml
  _layouts/signed.html
  index_ko.md
Labels: translation

#2112 Update README_RU.md
  README_RU.md
Labels: translation

#2086 Create index_ru.md (russian translation)
  index_ru.md
Labels: needs changes, translation

#2152 Add Persian translation
  index_fa.md
Labels: translation

#2397 Update index_fa.md
  index_fa.md
Labels: translation

#2440 Update index_es.md
  index_es.md
Labels: translation

#2514 Fix Ukrainian translation
  README_UA.md
Labels: translation

#2526 Update README_RU.md
  README_RU.md
Labels: translation

#2807 Update index_de.md
  index_de.md
Labels: translation

#2732 Update Vietnamese translation.
  index_vi.md
Labels: translation

#2768 Add link to Tagalog translation
  _layouts/signed.html
  _layouts/signed_rtl.html
Labels: translation

#2857 Create Alex-Malkov
  _data/signed/Alex-Malkov.yaml
Labels: needs changes

#2913 Update index_zh_cn.md
  index_zh_cn.md
Labels: translation

#2964 Add translations in Portuguese (pt-PT)
  README_PT-PT.md
  _includes/translations.html
  index_pt_pt.md
Labels: translation

#2921 add alternative ways to sign
  index_fa.md
Labels: translation

#2914 Enhance index_fr translation
  index_fr.md
Labels: translation

#2697 Updated Dutch translation
  README_NL.md
Labels: needs changes

#2970 Add JP translation
  README_JP.md
  index_jp.md
Labels: translation

#2906 Create tamizhis5n
  _data/signed/tamizhis5n.yaml
Labels: needs changes

#2932 Create ljmanso
  _data/signed/ljmanso
Labels: needs changes

#3169 yeah
  _data/signed/0x0000ff.yaml
Labels: needs changes

#3380 Update Tagalog translation
  README_tl.md
  _translations/index_tl.md
Labels: translation

#3410 Tagalog translation of social media image
  assets/social-media-preview_tl_PH.png
Labels: translation

#3281 Add my signature (aaronfranke)
  _data/gpg/aaronfranke/index.md.asc
  _data/gpg/aaronfranke/key0x40A1750B977E56BF.asc
  _data/signed/aaronfranke.yaml
Labels: needs changes

#3413 ADD Tamil translation
  _translations/index_ta.md
Labels: translation

#3440 fix: fix a typo
  _translations/index_fa.md
Labels: translation

#3431 Line wrap and nitpick Vietnamese translation
  _translations/index_vi.md
Labels: translation

#2764 Latvian translation
  README_LV.md
  _translations/index_lv.md
Labels: translation

#3672 Create pkalda.yaml
  _data/signed/pkalda.yaml
Labels: needs changes

#3753 Create Holger Blasum
  _data/signed/hblasum.yaml
Labels: needs changes

#3756 Create wiredancer.yaml
  _data/signed/wiredancer.yaml
Labels: needs changes

#3785 Create Andreas Artz
  _data/signed/AndreasArtz.yaml
Labels: needs changes

#3798 Add signature forAlexander Mcmahon
  _data/signed/alexander-mcmahon.yaml
Labels: needs changes

#3805 Create index_gr.md
  _translations/index_gr.md
Labels: needs changes, translation

#3820 Add links to Russian translation and small corrections
  _translations/index_ru.md
Labels: priority

#3827 Add arabic social media preview
  assets/social-media-preview_ar.png
Labels: needs changes

#3815 Portuguese Social Image
  _translations/index_pt_pt.md
  assets/social-media-preview_pt_PT.png
Labels: needs changes

#3838 social-media-preview_pl_PL.png: add Polish translation
  _translations/index_pl.md
  assets/social-media-preview_pl_PL.png
Labels: needs changes

#3877 Create mtcw.yaml
  _data/signed/mtcw.yaml
Labels: needs changes

#3366 Create justafreaky
  _data/signed/justafreaky
Labels: needs changes

#3569 Create IgorMarkiv
  _data/signed/IgorMarkiv.yaml
Labels: needs changes

#3749 Create michalzuchowski.yaml
  _data/signed/michalzuchowski.yaml
Labels: needs changes

#3577 Create amon22.yaml
  _data/signed/amon22.yaml
Labels: needs changes

#3906 Update italian and french transaltion
  _data/signed/franpoli.yaml
  _translations/index_fr.md
  _translations/index_it.md
  assets/social-media-preview_fr_FR.png
  assets/social-media-preview_it_IT.png
Labels: translation

#3918 Update and polish README_ZH-CN
  README_ZH-CN.md
Labels: translation

#3919 Update Tagalog translation of README
  README_TL.md
Labels: translation

#3933 Update Vietnamese translation
  README.md
  README_VI.md
  _translations/index_vi.md
  assets/social-media-preview_vi_VN.png
Labels: translation

#3954 Update chatroom links README_AL.md
  README_AL.md
Labels: translation

#3971 feat: translate social media preview and readme
  README_FA.md
  _translations/index_fa.md
  assets/social-media-preview_fa.png
Labels: translation

#4045 Create README_GR.md
  README_GR.md
Labels: translation

#4051 Update README_UA.md
  README_UA.md
Labels: translation

#4123 Create nikita-yfh.yaml
  _data/signed/nikita-yfh.yaml
Labels: help needed

#4135 Add nphantasm.yaml
  _data/signed/nphantasm.yaml
Labels: help needed

#4138 Create DebianCommunityNewsTeam.yaml
  _data/signed/DebianCommunityNewsTeam.yaml
Labels: help needed

#4181 Create RogRogerson.yaml
  _data/signed/RogRogerson.yaml
Labels: help needed

#4311 Create rcfoster1111.yaml
  _data/signed/rcfoster1111.yaml
Labels: needs changes

#4368 Updated Italian Translation
  _translations/index_it.md
Labels: translation

#4379 Free to RSM
  _data/signed/MaxErmolenko
Labels: needs changes

#4424 Create huihoo
  _data/signed/huihoo.yaml
Labels: needs changes

#4405 Create dlarge6522
  _data/signed/dlarge6522
Labels: needs changes

#4465 fix typo in ru readme
  README_RU.md
Labels: translation

#4508 Signed by chusiang.
  README_ZH-TW.md
  _data/signed/chusiang.yaml
Labels: translation

#4575 Create Eugene
  _data/signed/Eugene01012.yaml
Labels: needs changes

#4633 Create govnomocha.yaml
  _data/signed/govnomocha.yaml
Labels: needs changes

#4641 Create oh-fugg.yaml
  _data/signed/oh-fugg.yaml
Labels: needs changes

#4675 Create deivan.yaml
  _data/signed/deivan.yaml
Labels: needs changes

#4702 Create torsumy.yaml
  _data/signed/torsumy.yaml
Labels: help needed

#4751 Update README_TR.md
  README_TR.md
Labels: translation

#4757 Add Swedish translation
  README_SE.md
  _translations/index_se.md
  assets/social-media-preview_se_SE.png
Labels: translation

#4760 Finnish translation
  _translations/index_fi.md
Labels: translation

#4796 Update index_fi.md
  _translations/index_fi.md
Labels: translation

#4786 Improve Polish translation
  _translations/index_pl.md
Labels: translation

#4800 Update README_FI.md
  README_FI.md
Labels: translation

#4805 Fix duplicate Polish 'just as much'
  _translations/index_pl.md
Labels: translation

#4787 Create kulig.yaml
  _data/signed/kulig.yaml
Labels: needs changes

#4911 Update 404.html
  404.html
Labels: help needed

#5014 Social Media Preview: make Turkish version
  _translations/index_tr.md
  assets/social-media-preview_tr_TR.png
Labels: needs changes

#5124 Update Russian README
  README_RU.md
Labels: translation

#5160 Improving french README.md translation.
  README_FR.md
Labels: translation

#5202 Create rasul-gasanov.yaml
  _data/signed/rasul-gasanov.yaml
Labels: needs changes

#5216 Improving french translation of index.md.
  _translations/index_fr.md
Labels: translation

#5166 Create matesitox.yaml
  _data/signed/matesitox.yaml
Labels: needs changes

#5065 Armenian translation
  README_HY.md
  _translations/index_hy.md
Labels: help needed, translation

#5371 Create jschwartzenberg.yaml
  _data/signed/jschwartzenberg.yaml
Labels: needs changes
