Repository rms-support-letter/rms-support-letter.github.io, pull requests merged in 2021-04, with the labels that each got.

#5434 Create Monu_serg.yaml
  _data/signed/Monu_serg.yaml
Labels: needs changes

#5513 use native words alongside english ones
  README_RS.md
Labels: translation

#5531 Automated hreflang generation
  _includes/head.html
  _includes/hreflangs.html
  _translations/index_el.md
  _translations/index_gl.md
  _translations/index_ja.md
  _translations/index_sq.md
  _translations/index_sr.md
  _translations/index_sv.md
  _translations/index_uk.md
  _translations/index_zh_hans.md
  _translations/index_zh_hant.md
Labels: needs changes, translation

#5611 Create VladimirOsintsev
  _data/signed/VladimirOsintsev.yaml
Labels: needs changes

#5617 Create JasonCotman
  _data/signed/JasonCotman.yaml
Labels: needs changes

#5621 Signed by Aleokheen
  _data/signed/aleokheen.yaml
Labels: needs changes

#5609 Create Kyle De'Vir.yaml
  _data/signed/KyleDeVir.yaml
Labels: needs changes

#5635 Create andrei_ilin.md
  _data/signed/andrei_ilin.md
Labels: needs changes

#5760 Create mdeblin.yaml
  _data/signed/mdeblin.yaml
Labels: needs changes

#5833 Add Lombard translation
  _translations/index_lmo.md
Labels: help needed

#5842 Create s-borisovskiy.yaml
  _data/signed/s-borisovskiy.yaml
Labels: needs changes

#5876 Create LucaCazzaniga
  _data/signed/LucaCazzaniga.yaml
Labels: needs changes

#5872 Create johndoe02
  _data/signed/johndoe02.yaml
Labels: needs changes

#6083 Create <Alekseev Konstantin>.yaml
  _data/signed/AlekseevKonstantin.yaml
Labels: needs changes

#6196 Create pashok6798
  _data/signed/pashok6798.yaml
Labels: needs changes

#6241 Create leins275.yml
  _data/signed/leins275.yaml
Labels: needs changes

#6283 Create RomanKlimov.yaml
  _data/signed/RomanKlimov.yaml
Labels: needs changes

#6304 Create fedor.yaml
  _data/signed/fedor.yaml
Labels: needs changes

#6334 Create DmitryNevolin.yaml
  _data/signed/DmitryNevolin.yaml
Labels: help needed

#6479 Fix Vietnamese flag emoji
  README.md
  README_VI.md
Labels: translation

#6484 Added Afrikaans translations
  README.md
  README_AF.md
  _translations/index_af.md
Labels: translation

#6501 Create kain728.yaml
  _data/signed/kain728.yaml
Labels: needs changes

#6725 Syncing Ukrainian translation.
  README_UA.md
Labels: translation

#6754 Add social preview in Ukrainian
  _translations/index_uk.md
  assets/social-media-preview_uk_UA.png
Labels: translation

#6791 Correct syntax in Greek translation.
  _translations/index_el.md
Labels: translation

#6989 Add Armenian to the list of translations
  README.md
Labels: translation
